[package]
name = "chess-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = []
search-trace = ["chess-search/search-trace"]
context-history = ["chess-search/context-history"]

[dependencies]
chess-core = { path = "../chess-core" }
chess-search = { path = "../chess-search" }

[lints]
workspace = true
