#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv) != 3:
    raise SystemExit('usage: apply_v18_root_verify.py SEARCH.py TOP_K')
p=Path(sys.argv[1]); k=int(sys.argv[2])
if k < 2 or k > 12: raise SystemExit('TOP_K must be 2..12')
s=p.read_text()
old='''        else:\n            score, aborted = _negamax(\n                board, -side, child_castling, child_ep, child_halfmove, child_depth,\n                -alpha - 1, -alpha, np.int64(1), nodes, max_nodes, hard_deadline_ticks,\n                pseudo_stack, move_stack, score_stack, eval_stack, history_keys, history_count,\n                path_keys, killers, quiet_history, move_context_stack, hash_keys, hash_moves, history_contexts, student_edges, tt_table,\n            )\n            if not aborted and -score > alpha:\n                score, aborted = _negamax(\n                    board, -side, child_castling, child_ep, child_halfmove, child_depth,\n                    -INFINITY, -alpha, np.int64(1), nodes, max_nodes, hard_deadline_ticks,\n                    pseudo_stack, move_stack, score_stack, eval_stack, history_keys, history_count,\n                    path_keys, killers, quiet_history, move_context_stack, hash_keys, hash_moves, history_contexts, student_edges, tt_table,\n                )\n'''
new=f'''        elif index < {k}:\n            # Verify the best-ordered root alternatives without scout-only pruning.  The child\n            # window still only asks the mathematically necessary question: can this move beat\n            # the current root alpha?  Unlike a one-point scout, this disables selective\n            # scout-only RFP/null/futility at ply 1.\n            score, aborted = _negamax(\n                board, -side, child_castling, child_ep, child_halfmove, child_depth,\n                -INFINITY, -alpha, np.int64(1), nodes, max_nodes, hard_deadline_ticks,\n                pseudo_stack, move_stack, score_stack, eval_stack, history_keys, history_count,\n                path_keys, killers, quiet_history, move_context_stack, hash_keys, hash_moves, history_contexts, student_edges, tt_table,\n            )\n        else:\n            score, aborted = _negamax(\n                board, -side, child_castling, child_ep, child_halfmove, child_depth,\n                -alpha - 1, -alpha, np.int64(1), nodes, max_nodes, hard_deadline_ticks,\n                pseudo_stack, move_stack, score_stack, eval_stack, history_keys, history_count,\n                path_keys, killers, quiet_history, move_context_stack, hash_keys, hash_moves, history_contexts, student_edges, tt_table,\n            )\n            if not aborted and -score > alpha:\n                score, aborted = _negamax(\n                    board, -side, child_castling, child_ep, child_halfmove, child_depth,\n                    -INFINITY, -alpha, np.int64(1), nodes, max_nodes, hard_deadline_ticks,\n                    pseudo_stack, move_stack, score_stack, eval_stack, history_keys, history_count,\n                    path_keys, killers, quiet_history, move_context_stack, hash_keys, hash_moves, history_contexts, student_edges, tt_table,\n                )\n'''
if s.count(old) != 1: raise SystemExit(f'root verify patch mismatch: {s.count(old)}')
p.write_text(s.replace(old,new,1))
