#!/usr/bin/env python3
"""Defer expensive child state until a V14 move survives shallow pruning.

The exact V14 search advances the full 64-lane student accumulator and computes repetition/history
identity before late-quiet futility can discard a move. This patch prepares the student feature
changes as four scalar encoded deltas, advances only the exact V13 prefix, makes the move and runs
the existing check/futility/LMR gate. Surviving moves then materialise the H64 tail and child key.
"""
from pathlib import Path
import sys

p=Path(sys.argv[1]);s=p.read_text()
anchor='''@njit(cache=False)\ndef _negamax(\n'''
helpers='''@njit(cache=False, inline="always")\ndef _student_absolute_feature(signed_piece: int, square: int) -> int:\n    color_base = 0 if signed_piece > 0 else 384\n    return color_base + (abs(signed_piece) - 1) * 64 + square\n\n\n@njit(cache=False, inline="always")\ndef _prepare_student_move_deltas(\n    board: np.ndarray, side: int, move: int\n) -> tuple[int, int, int, int]:\n    from_square = move_from(move)\n    to_square = move_to(move)\n    promotion = move_promotion(move)\n    moving_signed = int(board[from_square])\n    placed_signed = side * promotion if promotion else moving_signed\n    d0 = -(_student_absolute_feature(moving_signed, from_square) + 1)\n    d1 = _student_absolute_feature(placed_signed, to_square) + 1\n    d2 = 0\n    d3 = 0\n    captured_square = to_square\n    captured_signed = int(board[to_square])\n    if move & FLAG_EP:\n        captured_square = to_square - 8 * side\n        captured_signed = int(board[captured_square])\n    if captured_signed != EMPTY:\n        d1 = -(_student_absolute_feature(captured_signed, captured_square) + 1)\n        d2 = _student_absolute_feature(placed_signed, to_square) + 1\n    if move & FLAG_CASTLE:\n        if to_square == 6:\n            rook_from, rook_to = 7, 5\n        elif to_square == 2:\n            rook_from, rook_to = 0, 3\n        elif to_square == 62:\n            rook_from, rook_to = 63, 61\n        else:\n            rook_from, rook_to = 56, 59\n        rook_signed = side * ROOK\n        d2 = -(_student_absolute_feature(rook_signed, rook_from) + 1)\n        d3 = _student_absolute_feature(rook_signed, rook_to) + 1\n    return d0, d1, d2, d3\n\n\n@njit(cache=False, inline="always")\ndef _apply_student_encoded_delta(accumulator: np.ndarray, encoded: int) -> None:\n    if encoded == 0:\n        return\n    sign = 1\n    feature = encoded - 1\n    if encoded < 0:\n        sign = -1\n        feature = -encoded - 1\n    for neuron in range(STUDENT_HIDDEN):\n        accumulator[neuron] += sign * int(STUDENT_FEATURE_WEIGHTS[feature, neuron])\n\n\n@njit(cache=False, inline="always")\ndef _advance_prepared_student_into(parent: np.ndarray, child: np.ndarray, d0: int, d1: int, d2: int, d3: int) -> None:\n    for neuron in range(STUDENT_HIDDEN):\n        child[neuron] = parent[neuron]\n    _apply_student_encoded_delta(child, d0)\n    _apply_student_encoded_delta(child, d1)\n    _apply_student_encoded_delta(child, d2)\n    _apply_student_encoded_delta(child, d3)\n\n\n@njit(cache=False)\ndef _negamax(\n'''
if s.count(anchor)!=1:raise SystemExit(f'negamax anchor count={s.count(anchor)}')
s=s.replace(anchor,helpers,1)
old='''        child_halfmove = _next_halfmove_clock(board, move, halfmove_clock)\n        _advance_eval_state_into(board, side, move, eval_stack[ply], eval_stack[ply + 1])\n        child_castling, child_ep, captured_piece, captured_square = make_move_inplace(\n            board, side, castling, ep_square, move\n        )\n        path_keys[ply + 1] = _child_position_key(\n            board,\n            side,\n            castling,\n            ep_square,\n            move,\n            child_castling,\n            child_ep,\n            captured_piece,\n            captured_square,\n            path_keys[ply],\n        )\n        history_contexts[ply + 1] = _child_history_context(\n            current_context, current_key, child_halfmove\n        )\n\n        # Adaptive verified LMR v3. Captures/promotions, both killers, checks, nodes in check and\n'''
new='''        child_halfmove = _next_halfmove_clock(board, move, halfmove_clock)\n        sd0, sd1, sd2, sd3 = _prepare_student_move_deltas(board, side, move)\n        _advance_eval_state_into(\n            board, side, move,\n            eval_stack[ply, :EVAL_V13_WIDTH],\n            eval_stack[ply + 1, :EVAL_V13_WIDTH],\n        )\n        child_castling, child_ep, captured_piece, captured_square = make_move_inplace(\n            board, side, castling, ep_square, move\n        )\n\n        # Adaptive verified LMR v3. Captures/promotions, both killers, checks, nodes in check and\n'''
if s.count(old)!=1:raise SystemExit(f'child-state pre-prune anchor count={s.count(old)}')
s=s.replace(old,new,1)
old2='''        if futility_candidate and not gives_check:\n            undo_move_inplace(board, side, move, captured_piece, captured_square)\n            continue\n\n        if gives_check:\n            reduction = 0\n'''
new2='''        if futility_candidate and not gives_check:\n            undo_move_inplace(board, side, move, captured_piece, captured_square)\n            continue\n\n        _advance_prepared_student_into(\n            eval_stack[ply, STUDENT_OFFSET:EVAL_WIDTH],\n            eval_stack[ply + 1, STUDENT_OFFSET:EVAL_WIDTH],\n            sd0, sd1, sd2, sd3,\n        )\n        path_keys[ply + 1] = _child_position_key(\n            board, side, castling, ep_square, move, child_castling, child_ep,\n            captured_piece, captured_square, path_keys[ply],\n        )\n        history_contexts[ply + 1] = _child_history_context(current_context, current_key, child_halfmove)\n\n        if gives_check:\n            reduction = 0\n'''
if s.count(old2)!=1:raise SystemExit(f'post-prune anchor count={s.count(old2)}')
s=s.replace(old2,new2,1)
p.write_text(s)
