[package]
name = "chess-uci"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = []
search-trace = ["chess-engine/search-trace"]
context-history = ["chess-engine/context-history"]

[dependencies]
chess-core = { path = "../chess-core" }
chess-engine = { path = "../chess-engine" }

[lints]
workspace = true
